services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ngelive_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./cache:/app/cache
    networks:
      - ngelive_network

networks:
  ngelive_network:
    driver: bridge
